# Generated by Django 4.2.3 on 2023-08-03 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essayexpert', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubDiscipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_discipline', to='essayexpert.discipline')),
            ],
        ),
    ]
