# Generated by Django 4.2.3 on 2023-08-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essayexpert', '0003_papertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=7.0, max_digits=12)),
            ],
        ),
    ]
