# Generated by Django 4.2.3 on 2023-08-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essayexpert', '0005_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discipline',
            field=models.CharField(choices=[('Health', 'Health'), ('Art', 'Art')], max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='ppt',
            field=models.CharField(blank=True, choices=[], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_of_paper',
            field=models.CharField(choices=[('History', 'History'), ('Essay', 'Essay')], max_length=100),
        ),
        migrations.AlterField(
            model_name='powerpoint',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
