# Generated by Django 4.2.3 on 2023-08-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essayexpert', '0006_alter_order_discipline_alter_order_ppt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ppt',
            field=models.CharField(blank=True, choices=[(4, 4)], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='powerpoint',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
