# Generated by Django 4.2.3 on 2023-08-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essayexpert', '0007_alter_order_ppt_alter_powerpoint_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerpoint',
            name='price',
            field=models.DecimalField(decimal_places=2, default=3.0, editable=False, max_digits=12),
        ),
    ]
