# Generated by Django 4.2.3 on 2023-08-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essayexpert', '0008_alter_powerpoint_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='powerpoint',
            name='count',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
