# Generated by Django 4.2.3 on 2023-08-03 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essayexpert', '0009_alter_powerpoint_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'get_latest_by': 'createdAt'},
        ),
        migrations.AddField(
            model_name='order',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 8, 3, 18, 30, 59, 497042, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='ppt',
            field=models.CharField(blank=True, choices=[(4, 4), (33, 33)], max_length=100, null=True),
        ),
    ]
